### Variables
# @baseUrl =   https://myapp.amroaltayeb14.workers.dev 
# For local testing, uncomment the line below:
@token = eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MTIsInJvbGUiOiJhZG1pbiIsInVzZXJOYW1lIjoiYW1ybyIsImlhdCI6MTc2NTc2MjYwNCwiZXhwIjoxNzY2MzY3NDA0fQ.__ScGEP3P__IZThMOhK3C9CJL3aCRJfLmnZVbpBF6MY
@baseUrl = http://localhost:8787

### signup
POST {{baseUrl}}/users/signup
Content-Type: application/json

{
  "userName": "amro",
  "email": "amro@gmail.com",
  "password": "123456",
  "role": "admin"
}
### login
POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "email": "amro@gmail.com",
  "password": "123456"
}
### get student
GET {{baseUrl}}/users/students
### get admins
GET {{baseUrl}}/users/admin
### get teachers
GET {{baseUrl}}/users/teachers
### delete user
DELETE {{baseUrl}}/users/12
Authorization: Bearer {{token}}


###################SCHOOL###################
### create school
POST {{baseUrl}}/schools
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "almoh"
}
### get schools
GET {{baseUrl}}/schools

